# Generated by Django 3.2.10 on 2022-01-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_banner_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Pagina inicial', 'verbose_name_plural': 'paginas iniciais'},
        ),
    ]
